In [1]:
import numpy as np

In [3]:
#Arithematic operations
a1 = np.array([1,2,3,4,5])
a2 = np.array([6,7,8,9,10])

In [4]:
a1 + a2 # elem should be same in both a1 and a2 otherwise it will throw an error

array([ 7,  9, 11, 13, 15])

In [5]:
a1 - a2

array([-5, -5, -5, -5, -5])

In [6]:
a1 * a2

array([ 6, 14, 24, 36, 50])

In [7]:
a1 / a2

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [8]:
a1 // a2 #// called as floor divison here val will be in int only eg.- 0,,1,2,3 etc

array([0, 0, 0, 0, 0])

In [9]:
a1 ** a2 #power opn **

array([      1,     128,    6561,  262144, 9765625])

In [10]:
#BROADCASTING - used to add single elem to multiple elem in list 
l = [10,20,30,40,50]
arr = np.array(l)

In [11]:
arr + 10

array([20, 30, 40, 50, 60])

In [13]:
arr2 = np.arange(1,21).reshape(5,4)
arr2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [16]:
arr2 + 10 # change is temporary 
arr2 = arr2 + 10 #change is permanent in whole notebook 
arr2

array([[21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32],
       [33, 34, 35, 36],
       [37, 38, 39, 40]])

In [ ]:
#DEEP AND SHALLOW COPY
a = np.arange(1,21)