In [7]:
import numpy as np

In [8]:
#Basic array creation
arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [9]:
a = [1,2,3,"hello",5.5]
a

[1, 2, 3, 'hello', 5.5]

In [10]:
b = np.array(a)
b

array(['1', '2', '3', 'hello', '5.5'], dtype='<U32')

In [11]:
c = [1,2,3,5.5]
c

[1, 2, 3, 5.5]

In [12]:
d = np.array(c)
d

array([1. , 2. , 3. , 5.5])

In [13]:
l = [[1,2,3],[4,5,6],[7,8,9]]
l

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [14]:
np.array(l)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
arr = np.arange(1,11,2)
arr

array([1, 3, 5, 7, 9])

In [16]:
# arr = np.zeros(5)
# arr
arr1 = np.zeros((5,5))
arr1
arr2 = np.ones((5,4))
arr2

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [17]:
# Linear Space-evenly space btwn elem
# for vector([1,2,3,4])
# for matrix ([[1,2,3,4]])
arr = np.linspace(1,10,5)
arr
arr = np.linspace(1,5,10)
arr
arr = np.linspace(1,10,20)
arr

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [18]:
# Random Generation funcn
arr = np.random.rand(10)#can have val btwn 0 and 1= normalization
arr
arr1 = np.random.randn(5)#Here we use concept of Standardization where value is btwn -3 and 3
arr1

array([ 0.850217  ,  0.25850577,  2.12343982,  1.03391799, -1.35948924])

In [19]:
arr = np.random.randint(8)#Generates random no btwn 0 and 8
arr
arr1 = np.random.randint(1,15,10)
arr1

array([14,  4,  5, 11,  3,  4, 12,  1,  9, 11], dtype=int32)

In [20]:
#Array attributes
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [21]:
arr.shape

(3, 3)

In [22]:
arr.size

9

In [23]:
arr.dtype

dtype('int64')

In [24]:
#Array methods
arr.min()
arr.max()
arr.sum()

np.int64(45)

In [25]:
np.sum(arr,axis = 0) #axis = 0 vertical elem(coln wise) sum and if axis = 1 horizontal (row wise)elem sum
np.sum(arr,axis = 1)

array([ 6, 15, 24])

In [26]:
arr.mean()

np.float64(5.0)

In [27]:
arr.std()#std deviation

np.float64(2.581988897471611)

In [28]:
arr.argmax()#Tells maxm value index here elem 9 is at index 8 which is maxm
arr.argmin()

np.int64(0)

In [29]:
#Reshaping and Resizing
arr = np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [31]:
arr = arr.reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])